### ISSUE TITLE
Mirror Cover Deploy/Retract sequence 

### ISSUE THREAD

**Issue by isotuela** [lsst-ts/ts_tma_tma-documentation_eui-manual-english#3]
Hi Julen, 
Regarding https://ts-tma.lsst.io/docs/tma_eui-manual-english/02_Monitor%26Control/021_MirrorCoverGeneralView.html#mirror-cover-deploy-retract-sequence, 
I think it would be useful to add a section (similar to the LP we did today) with the specific order of buttons and indicators changes while you go through the complete process of successfully deploying/retracting MC. 
I mean something like this, maybe in a table form, or do you think it's overkill?

0. *Any precondition* like elevation higher than something, drives off/on, OSS off/on etc.
1. Power on the *Mirror Cover Locks* (MCLs) in the screen (link to page) pressing *ALL*, and then *ON*. The status will change to "Active"
2. From section 2. Choose *ALL*,  or the MC you will operate. 
3. Turn *ON* MC power in section 3. Status indicator will change to "Active"
4. Select the operation *DEPLOY*
5. All the MCLs are moved to the unlock position (Are they moved with the DEPLOY/RETRACT button, right). Indicators for "Unlocked" go from grey to green, whereas the "Locked" turns grey. 
6. When the MCLs reach the unlocked position, two MCs are deployed (Y+ and Y-)
7. When the Ys MCs reach the extended position, the other two MCs are moved (X+ and X-)
8. When the four MCs reach the extended position, the command is *DEPLOY* ended successfully
9. Turn *OFF* Mirror Cover Power in section 3. Indicators baablsa
10. *LOCK* MC from the MCL screen. Turn *OFF* will send the MCLs status back to "Idle".
11. Mirror covers extended, locked and powered off. 

The part in bold of the sentences "Deploy sequence: this sequence is for extending all Mirror Covers (MCs), **which requires the MCLs to be in the unlocked position to permit motion.**" sounds a bit confusing to me. It looks like you have to unlock them manually, but the *DEPLOY* command does it right?. Same for the Retract sequence sentence. 

I hope this makes sense. Let me know if you have questions.

**Comment by julen-garcia** [comment]
added, please check and let me know

**Comment by isotuela** [comment]
Thank you @julen-garcia ! 
It looks good to me. Two minor comment, more format-wise than anything
-  Add a . at the end of the bullet points, when they are sentences, as most of these bullets are. 
-  As these steps must be executed in a certain order, I think it'd be better to number the list. Instead of starting with a `-`, if you start with `1.` and markdown will take care of it. 

Thank you for all your help!

**Comment by julen-garcia** [comment]
@isotuela better now?

**Comment by isotuela** [comment]
Indeed. Thank you so much!
